### ISSUE TITLE
Infected file regex propositions

### ISSUE THREAD

**Issue by sigmounte** [Nexylan/PHPAV#3]
Regex qui fonctionnent bien , et qui seraient bien d'intégrées a PHPav , parce que PHPav c'est bien , c'est bon , mangez en 

``` bash
grep "\"64_decode" >> result.txt

grep "\\x[0-9a-f][0-9a-f]\\x[0-9a-f][0-9a-f]\\x[0-9a-f][0-9a-f]\\x[0-9a-f][0-9a-f]\\x[0-9a-f][0-9a-f]\\x[0-9a-f][0-9a-f]\\x[0-9a-f][0-9a-f]" >> result.txt

grep ";global" >> result.txt

grep "[0-9a-zA-Z]\].\$GLOBALS" >> result.txt
```

**Comment by gallart** [comment]
Bonjour,

Merci pour la proposition, mais peux-tu en dire plus ?

**Comment by soullivaneuh** [comment]
Can you elaborate a bit about how each regex work?

**Comment by soullivaneuh** [comment]
Please use English sentences to make it understandable by everyone.

**Comment by sigmounte** [comment]
If any of the four regex match , this is an infected file

**Comment by soullivaneuh** [comment]
Yes. But why this is considered as infected?

**Comment by gallart** [comment]
How did you make sure they don't match legit files?

**Comment by sigmounte** [comment]
this is fingerprinting based , not code analysis based

**Comment by gallart** [comment]
Fingerprints have been updated in webshells.txt. Let us know;

**Comment by soullivaneuh** [comment]
I close this issue because of no answers for a while.

Feel free to re-open it if needed.
